version: "3.9"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d bank"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 3s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:password@db:5432/bank?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
volumes:
  data-volume: