// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  password_hashed,
  fullname
) VALUES (
  $1, $2, $3
) RETURNING username, password_hashed, fullname, created_at, password_updated_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	PasswordHashed string `json:"password_hashed"`
	Fullname       string `json:"fullname"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHashed, arg.Fullname)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHashed,
		&i.Fullname,
		&i.CreatedAt,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, password_hashed, fullname, created_at, password_updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHashed,
		&i.Fullname,
		&i.CreatedAt,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  password_hashed = COALESCE($1, password_hashed),
  password_updated_at = COALESCE($2, password_updated_at),
  fullname = COALESCE($3, fullname)
WHERE
  username = $4
RETURNING username, password_hashed, fullname, created_at, password_updated_at
`

type UpdateUserParams struct {
	PasswordHashed    pgtype.Text        `json:"password_hashed"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
	Fullname          pgtype.Text        `json:"fullname"`
	Username          string             `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.PasswordHashed,
		arg.PasswordUpdatedAt,
		arg.Fullname,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHashed,
		&i.Fullname,
		&i.CreatedAt,
		&i.PasswordUpdatedAt,
	)
	return i, err
}
